"""feat: add addresses logical delete

Revision ID: 3390fc45520d
Revises: 12cbb832b5a3
Create Date: 2024-08-26 17:04:06.344761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3390fc45520d'
down_revision: Union[str, None] = '12cbb832b5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('deleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'deleted')
    # ### end Alembic commands ###
