apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: ecommerce
type: Opaque
stringData:
  postgres-password: postgres
  order-app-password: 123abc
  inventory-app-password: 123abc
  delivery-app-password: 123abc
  mongo-root-password: mongo
