services:
  inventory_service:
    build:
      context: ./inventory
      dockerfile: Dockerfile.inventory
    ports:
      - "8001:8001"
    volumes:
      - ./inventory:/app
    networks:
      - ecommerce_network
    command: uvicorn inventory_service:app --host 0.0.0.0 --port 8001 --reload

  orders_service:
    build:
      context: ./orders
      dockerfile: Dockerfile.orders
    ports:
      - "8002:8002"
    volumes:
      - ./orders:/app
    networks:
      - ecommerce_network
    command: uvicorn orders_service:app --host 0.0.0.0 --port 8002 --reload

  payments_service:
    build:
      context: ./payments
      dockerfile: Dockerfile.payments
    ports:
      - "8003:8003"
    volumes:
      - ./payments:/app
    networks:
      - ecommerce_network
    command: uvicorn payments_service:app --host 0.0.0.0 --port 8003 --reload

  delivery_service:
    build:
      context: ./delivery
      dockerfile: Dockerfile.delivery
    ports:
      - "8004:8004"
    volumes:
      - ./delivery:/app
    networks:
      - ecommerce_network
    command: uvicorn delivery_service:app --host 0.0.0.0 --port 8004 --reload

networks:
  ecommerce_network:
    driver: bridge
