x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong_db
  KONG_PG_HOST: postgres
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kongpassword

services:
  inventory_service:
    build:
      context: ./inventory
      dockerfile: Dockerfile.inventory
    ports:
      - "8001:8001"
    volumes:
      - ./inventory:/app
    networks:
      - ecommerce_network
    command: uvicorn inventory_service:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      - rabbitmq

  orders_service:
    build:
      context: ./orders
      dockerfile: Dockerfile.orders
    ports:
      - "8002:8002"
    volumes:
      - ./orders:/app
    networks:
      - ecommerce_network
    command: uvicorn orders_service:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      - rabbitmq

  payments_service:
    build:
      context: ./payments
      dockerfile: Dockerfile.payments
    ports:
      - "8003:8003"
    volumes:
      - ./payments:/app
    depends_on:
      - mongo
    networks:
      - ecommerce_network
    command: uvicorn payments_service:app --host 0.0.0.0 --port 8003 --reload

  delivery_service:
    build:
      context: ./delivery
      dockerfile: Dockerfile.delivery
    ports:
      - "8004:8004"
    volumes:
      - ./delivery:/app
    networks:
      - ecommerce_network
    command: uvicorn delivery_service:app --host 0.0.0.0 --port 8004 --reload

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_ecommerce:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  mongo:
    image: mongo:8.0.0-rc11-jammy
    hostname: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_ecommerce:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - ecommerce_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - ecommerce_network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KC_DB=postgres
      # - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak_db
      # - KC_DB_USERNAME=keycloak
      # - KC_DB_PASSWORD=keycloakpassword
    ports:
      - "8070:8070"
    command:
      - "start-dev"
      - "--http-port=8070"
      - "--import-realm"
    networks:
      - ecommerce_network
    volumes:
      - ./conf/keycloak/realm.json:/opt/keycloak/data/import/realm.json
    # depends_on:
    #   - postgres

  kong-migrations:
    image: kong:3.4.0
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    networks:
      - ecommerce_network
    depends_on:
      - postgres

  kong:
    image: kong:3.4.0
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "0.0.0.0:8443:8443/tcp"
      - "0.0.0.0:8001:8001/tcp"
      - "0.0.0.0:8444:8444/tcp"
    volumes:
      - ./conf/kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    networks:
      - ecommerce_network
    depends_on:
      - kong-migrations

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_ecommerce:
  mongo_ecommerce:
