include:
  - docker-compose.yaml

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app/
    command: |
      python -m pytest tests -s -vv -x --cov . --cov-report=html:/app/reports/coverage --alluredir /app/allure-results
    environment:
      BROKER_HOST: rabbitmq
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: inventory
      DATABASE_USER: inventory_app
      DATABASE_PASSWORD: 123abc

  bdd:
    build:
      context: ./bdd
    volumes:
      - ./bdd:/app/
    command: behave
    networks:
      - inventory_network
    environment:
      BASE_URL: http://inventory_service:8001

  allure:
    build:
      context: .
      dockerfile: Dockerfile.allure
    volumes:
      - .:/app/
    ports:
      - "35741:35741"

networks:
  inventory_network:
    driver: bridge

volumes:
  postgres_inventory:
  mongo_inventory:
