apiVersion: batch/v1
kind: Job
metadata:
  name: delivery-migration-job
  namespace: ecommerce
spec:
  template:
    metadata:
      name: delivery-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: delivery-migration
          image: delivery:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "-c"]
          args:
            - "alembic -c migrations/alembic/alembic.ini upgrade head"
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: delivery
            - name: DATABASE_USER
              value: delivery_app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: delivery-app-password
