apiVersion: batch/v1
kind: Job
metadata:
  name: orders-migration-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: orders-migration
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: orders-migration
          image: dmenezesgabriel/orders:latest
          imagePullPolicy: Always
          command:
            [
              "alembic",
              "-c",
              "migrations/alembic/alembic.ini",
              "upgrade",
              "head",
            ]
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: order
            - name: DATABASE_USER
              value: order_app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: order-app-password
