apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: orders:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: INVENTORY_SERVICE_BASE_URL
              value: "http://inventory-service:8001/inventory"
            - name: BROKER_HOST
              value: rabbitmq
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: order
            - name: DATABASE_USER
              value: order_app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: order-app-password
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
