apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      automountServiceAccountToken: false
      containers:
        - name: orders
          image: dmenezesgabriel/orders:latest
          command:
            ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
              protocol: TCP
          env:
            - name: INVENTORY_SERVICE_BASE_URL
              value: "http://inventory-service:8001/inventory"
            - name: BROKER_HOST
              value: rabbitmq
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: order
            - name: DATABASE_USER
              value: order_app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: order-app-password
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
            requests:
              cpu: "0.5"
              memory: "128Mi"
              ephemeral-storage: "512Mi"
