apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-srv
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
