apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      automountServiceAccountToken: false
      containers:
        - name: inventory
          image: dmenezesgabriel/inventory:latest
          command:
            ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: BROKER_HOST
              value: rabbitmq
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: inventory
            - name: DATABASE_USER
              value: inventory_app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: inventory-app-password
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
            requests:
              cpu: "0.5"
              memory: "128Mi"
              ephemeral-storage: "512Mi"
