apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      automountServiceAccountToken: false
      containers:
        - name: inventory
          image: dmenezesgabriel/inventory:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: BROKER_HOST
              value: rabbitmq
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: inventory
            - name: DATABASE_USER
              value: inventory_app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: inventory-app-password
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
