"""feat: add product images and description

Revision ID: d8803f5582aa
Revises: ca89547f7e50
Create Date: 2024-08-25 15:05:31.074300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8803f5582aa'
down_revision: Union[str, None] = 'ca89547f7e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'images')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
