services:
  app:
    hostname: payments_service
    build:
      context: ./payments
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./payments:/app
    depends_on:
      - mongo
    networks:
      - payments_network
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - payments_network

  mongo:
    image: mongo:8.0.0-rc11-jammy
    hostname: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_payments:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - payments_network

networks:
  payments_network:
    driver: bridge

volumes:
  mongo_payments:
