CREATE DATABASE "order";
CREATE USER order_app WITH PASSWORD '123abc';
GRANT ALL PRIVILEGES ON DATABASE "order" TO order_app;

\c order
GRANT ALL PRIVILEGES ON SCHEMA public TO order_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO order_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO order_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO order_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO order_app;

---

CREATE DATABASE "inventory";
CREATE USER inventory_app WITH PASSWORD '123abc';
GRANT ALL PRIVILEGES ON DATABASE "inventory" TO inventory_app;

\c inventory
GRANT ALL PRIVILEGES ON SCHEMA public TO inventory_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO inventory_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO inventory_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO inventory_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO inventory_app;

---

CREATE DATABASE "delivery";
CREATE USER delivery_app WITH PASSWORD '123abc';
GRANT ALL PRIVILEGES ON DATABASE "delivery" TO delivery_app;

\c delivery
GRANT ALL PRIVILEGES ON SCHEMA public TO delivery_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO delivery_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO delivery_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO delivery_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO delivery_app;
