-- Order Service Database
CREATE DATABASE "order";
CREATE USER order_app WITH PASSWORD '123abc';
GRANT ALL PRIVILEGES ON DATABASE "order" TO order_app;

\c order
GRANT ALL PRIVILEGES ON SCHEMA public TO order_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO order_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO order_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO order_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO order_app;

-- Inventory Service Database
CREATE DATABASE "inventory";
CREATE USER inventory_app WITH PASSWORD '123abc';
GRANT ALL PRIVILEGES ON DATABASE "inventory" TO inventory_app;

\c inventory
GRANT ALL PRIVILEGES ON SCHEMA public TO inventory_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO inventory_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO inventory_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO inventory_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO inventory_app;

-- Delivery Service Database
CREATE DATABASE "delivery";
CREATE USER delivery_app WITH PASSWORD '123abc';
GRANT ALL PRIVILEGES ON DATABASE "delivery" TO delivery_app;

\c delivery
GRANT ALL PRIVILEGES ON SCHEMA public TO delivery_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO delivery_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO delivery_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO delivery_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO delivery_app;

-- Keycloak Database
CREATE DATABASE "keycloak_db";
CREATE USER keycloak WITH PASSWORD 'keycloakpassword';
GRANT ALL PRIVILEGES ON DATABASE "keycloak_db" TO keycloak;

\c keycloak_db
GRANT ALL PRIVILEGES ON SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO keycloak;

-- Kong Database
CREATE DATABASE "kong_db";
CREATE USER kong WITH PASSWORD 'kongpassword';
GRANT ALL PRIVILEGES ON DATABASE "kong_db" TO kong;

\c kong_db
GRANT ALL PRIVILEGES ON SCHEMA public TO kong;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kong;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kong;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO kong;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO kong;
